services:
  - type: web
    name: stack-webapp
    runtime: python
    plan: free
    autoDeployTrigger: commit
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT stack_webapp.wsgi:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: APP_TITLE
        value: Stack
      - key: HS_TOKEN
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DEBUG_USERID
        value: true
